### PR TITLE
DONE - Fix erb errors

### PR DESCRIPTION
**Pull request by rickstylz01**

### CODE REVIEW

**Comment by rashadmad** [comment]
You should really write a description, I would even suggest pictures if applicable. I really don't know what fixing erb errors is, not to say you need to explain it to me, just be more descriptive of what you are doing with pull request.

**Comment by markdamobi** [comment]
> You should really write a description, I would even suggest pictures if applicable. I really don't know what fixing erb errors is, not to say you need to explain it to me, just be more descriptive of what you are doing with pull request.

Not a bad suggestion. But Instead of writing a description though, another idea might be to just link to the [trello ticket](https://trello.com/c/zMTQud3d/88-fix-erb-errors) so you won't need to repeat the description.

**Comment by rashadmad** [comment]
> > You should really write a description, I would even suggest pictures if applicable. I really don't know what fixing erb errors is, not to say you need to explain it to me, just be more descriptive of what you are doing with pull request.
> 
> Not a bad suggestion. But Instead of writing a description here, another idea might be to just link to the [trello ticket](https://trello.com/c/zMTQud3d/88-fix-erb-errors) so you won't need to repeat the description.

good point.

**Comment by gcwokeup** [comment]
image
@rashadmad I kinda told him to just do that. There were a total of 108 things to fix. It would've been too long. I was just gonna paste the things that were changed when everything is done. @markdamobi that's a good idea.

**Comment by gcwokeup** [comment]
Errors that were fixed:
Running erblint w/o autocorrect
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.2-compliant syntax, but you are running 2.6.1.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Linting 31 files with 14 linters...

Layout/SpaceInsideHashLiteralBraces: Space inside { missing.
In file: app/views/home/contact.html.erb:3

Layout/SpaceInsideHashLiteralBraces: Space inside } missing.
In file: app/views/home/contact.html.erb:3

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/home/contact.html.erb:3

Tag `input` is self-closing, it must end with `/>`.
In file: app/views/home/contact.html.erb:19

Tag `input` is self-closing, it must end with `/>`.
In file: app/views/home/contact.html.erb:23

Layout/SpaceInsideHashLiteralBraces: Space inside { missing.
In file: app/views/home/policy.html.erb:3

Layout/SpaceInsideHashLiteralBraces: Space inside } missing.
In file: app/views/home/policy.html.erb:3

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/home/policy.html.erb:3

Layout/SpaceInsideHashLiteralBraces: Space inside { missing.
In file: app/views/home/policy.html.erb:23

Layout/SpaceInsideHashLiteralBraces: Space inside } missing.
In file: app/views/home/policy.html.erb:23

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/home/policy.html.erb:23

Layout/SpaceInsideHashLiteralBraces: Space inside { missing.
In file: app/views/home/policy.html.erb:31

Layout/SpaceInsideHashLiteralBraces: Space inside } missing.
In file: app/views/home/policy.html.erb:31

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/home/policy.html.erb:31

Layout/SpaceInsideHashLiteralBraces: Space inside { missing.
In file: app/views/home/policy.html.erb:37

Layout/SpaceInsideHashLiteralBraces: Space inside } missing.
In file: app/views/home/policy.html.erb:37

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/home/policy.html.erb:37

Layout/SpaceAfterColon: Space missing after colon.
In file: app/views/home/policy.html.erb:55

Layout/SpaceInsideHashLiteralBraces: Space inside { missing.
In file: app/views/home/policy.html.erb:55

Layout/SpaceInsideHashLiteralBraces: Space inside } missing.
In file: app/views/home/policy.html.erb:55

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/home/policy.html.erb:55

Layout/SpaceAfterColon: Space missing after colon.
In file: app/views/home/policy.html.erb:88

Layout/SpaceInsideHashLiteralBraces: Space inside { missing.
In file: app/views/home/policy.html.erb:88

Layout/SpaceInsideHashLiteralBraces: Space inside } missing.
In file: app/views/home/policy.html.erb:88

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/home/policy.html.erb:88

Layout/SpaceInsideHashLiteralBraces: Space inside { missing.
In file: app/views/home/policy.html.erb:103

Layout/SpaceInsideHashLiteralBraces: Space inside } missing.
In file: app/views/home/policy.html.erb:103

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/home/policy.html.erb:103

Layout/SpaceInsideHashLiteralBraces: Space inside { missing.
In file: app/views/home/policy.html.erb:118

Layout/SpaceInsideHashLiteralBraces: Space inside } missing.
In file: app/views/home/policy.html.erb:118

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/home/policy.html.erb:118

Layout/SpaceInsideHashLiteralBraces: Space inside { missing.
In file: app/views/home/policy.html.erb:127

Layout/SpaceInsideHashLiteralBraces: Space inside } missing.
In file: app/views/home/policy.html.erb:127

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/home/policy.html.erb:127

Layout/SpaceInsideHashLiteralBraces: Space inside { missing.
In file: app/views/home/policy.html.erb:134

Layout/SpaceInsideHashLiteralBraces: Space inside } missing.
In file: app/views/home/policy.html.erb:134

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/home/policy.html.erb:134

Layout/SpaceInsideHashLiteralBraces: Space inside { missing.
In file: app/views/home/policy.html.erb:144

Layout/SpaceInsideHashLiteralBraces: Space inside } missing.
In file: app/views/home/policy.html.erb:144

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/home/policy.html.erb:144

Layout/SpaceInsideHashLiteralBraces: Space inside { missing.
In file: app/views/home/policy.html.erb:163

Layout/SpaceInsideHashLiteralBraces: Space inside } missing.
In file: app/views/home/policy.html.erb:163

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/home/policy.html.erb:163

Layout/SpaceInsideHashLiteralBraces: Space inside { missing.
In file: app/views/home/policy.html.erb:174

Layout/SpaceInsideHashLiteralBraces: Space inside } missing.
In file: app/views/home/policy.html.erb:174

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/home/policy.html.erb:174

Layout/SpaceInsideHashLiteralBraces: Space inside { missing.
In file: app/views/home/policy.html.erb:188

Layout/SpaceInsideHashLiteralBraces: Space inside } missing.
In file: app/views/home/policy.html.erb:188

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/home/policy.html.erb:188

Layout/SpaceInsideHashLiteralBraces: Space inside { missing.
In file: app/views/home/policy.html.erb:203

Layout/SpaceInsideHashLiteralBraces: Space inside } missing.
In file: app/views/home/policy.html.erb:203

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/home/policy.html.erb:203

Layout/SpaceAfterColon: Space missing after colon.
In file: app/views/home/policy.html.erb:223

Layout/SpaceInsideHashLiteralBraces: Space inside { missing.
In file: app/views/home/policy.html.erb:223

Layout/SpaceInsideHashLiteralBraces: Space inside } missing.
In file: app/views/home/policy.html.erb:223

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/home/policy.html.erb:223

Layout/AlignHash: Align the elements of a hash literal if they span more than one line.
In file: app/views/home/policy.html.erb:234

Layout/SpaceAfterColon: Space missing after colon.
In file: app/views/home/policy.html.erb:234

Layout/SpaceInsideHashLiteralBraces: Space inside { missing.
In file: app/views/home/policy.html.erb:234

Layout/SpaceInsideHashLiteralBraces: Space inside } missing.
In file: app/views/home/policy.html.erb:235

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/home/policy.html.erb:234

Layout/SpaceAfterColon: Space missing after colon.
In file: app/views/home/policy.html.erb:242

Layout/SpaceInsideHashLiteralBraces: Space inside { missing.
In file: app/views/home/policy.html.erb:242

Layout/SpaceInsideHashLiteralBraces: Space inside } missing.
In file: app/views/home/policy.html.erb:242

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/home/policy.html.erb:242

Layout/SpaceInsideHashLiteralBraces: Space inside { missing.
In file: app/views/home/policy.html.erb:253

Layout/SpaceInsideHashLiteralBraces: Space inside } missing.
In file: app/views/home/policy.html.erb:254

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/home/policy.html.erb:253

Extra blank line detected.
In file: app/views/home/policy.html.erb:87

Layout/SpaceInsideHashLiteralBraces: Space inside { missing.
In file: app/views/home/about.html.erb:3

Layout/SpaceInsideHashLiteralBraces: Space inside } missing.
In file: app/views/home/about.html.erb:3

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/home/about.html.erb:3

Layout/SpaceInsideHashLiteralBraces: Space inside { missing.
In file: app/views/home/about.html.erb:22

Layout/SpaceInsideHashLiteralBraces: Space inside } missing.
In file: app/views/home/about.html.erb:22

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/home/about.html.erb:22

Layout/SpaceInsideHashLiteralBraces: Space inside { missing.
In file: app/views/home/about.html.erb:30

Layout/SpaceInsideHashLiteralBraces: Space inside } missing.
In file: app/views/home/about.html.erb:30

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/home/about.html.erb:30

Layout/SpaceInsideHashLiteralBraces: Space inside { missing.
In file: app/views/home/about.html.erb:38

Layout/SpaceInsideHashLiteralBraces: Space inside } missing.
In file: app/views/home/about.html.erb:38

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/home/about.html.erb:38

Layout/SpaceInsideHashLiteralBraces: Space inside { missing.
In file: app/views/home/about.html.erb:46

Layout/SpaceInsideHashLiteralBraces: Space inside } missing.
In file: app/views/home/about.html.erb:46

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/home/about.html.erb:46

Layout/SpaceInsideHashLiteralBraces: Space inside { missing.
In file: app/views/home/about.html.erb:57

Layout/SpaceInsideHashLiteralBraces: Space inside } missing.
In file: app/views/home/about.html.erb:57

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/home/about.html.erb:57

Layout/SpaceInsideHashLiteralBraces: Space inside { missing.
In file: app/views/home/about.html.erb:69

Layout/SpaceInsideHashLiteralBraces: Space inside } missing.
In file: app/views/home/about.html.erb:69

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/home/about.html.erb:69

Extra blank line detected.
In file: app/views/home/about.html.erb:64

Remove multiple trailing newline at the end of the file.
In file: app/views/home/about.html.erb:82

Missing a trailing newline at the end of the file.
In file: app/views/shared/_flash.html.erb:5

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/layouts/header.html.erb:1

Layout/SpaceAfterColon: Space missing after colon.
In file: app/views/layouts/header.html.erb:12

Layout/SpaceAfterColon: Space missing after colon.
In file: app/views/layouts/header.html.erb:18

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/layouts/header.html.erb:18

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/layouts/header.html.erb:18

Layout/SpaceAfterColon: Space missing after colon.
In file: app/views/layouts/header.html.erb:20

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/layouts/header.html.erb:20

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/layouts/header.html.erb:20

Use 1 space before `%>` instead of 0 space.
In file: app/views/layouts/header.html.erb:12

Use 1 space before `%>` instead of 2 space.
In file: app/views/layouts/header.html.erb:18

Use 1 space before `%>` instead of 2 space.
In file: app/views/layouts/header.html.erb:20

No space detected where there should be a single space.
In file: app/views/layouts/application.html.erb:10

Extra space detected where there should be no space.
In file: app/views/layouts/application.html.erb:13

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/users/show.html.erb:4

Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
In file: app/views/users/show.html.erb:4

108 error(s) were found in ERB files

**Pull request merged**
