### PR TITLE
For Trello card: Edit profile page image is not showing

### PR DESCRIPTION
**Pull request by WCW789**

### CODE REVIEW

**Comment by markdamobi** [comment]
@WCW789 good job taking care of this! When you get a chance, can you double check the requirement? Before your change, there was a "Change Picture" button below the placeholder. But after your change, the button is no longer there. I'm including screenshots to show the diff. 

before:
before

After:
after


Also, do you mind including a link back to the trello ticket in the pr description? It'll probably also be helpful to include screenshot in the description of what to expect from the change you made.

**Comment by WCW789** [comment]
Thanks for reviewing the PR, Mark!  Here is the link to the Trello card: https://trello.com/c/xO1mB6pW/113-edit-profile-page-image-is-not-showing

One of the requests was to remove "change picture for now", so I took it out.  From what I understand from the card, the main tasks were to get the profile pic showing and to take the change picture option out.  If anything should be revised, let me know.  thanks!

**Comment by markdamobi** [comment]
> One of the requests was to remove "change picture for now", so I took it out.
Ohh my bad then. Thanks for clarifying!

**Comment by uuunk** [comment]
Thanks @markdamobi and @WCW789! Merging in

**Pull request merged**
